framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 1
                    # milliseconds delay
                    delay: 1000
                    # causes the delay to be higher before each retry
                    # e.g. 1-second delay, 2 seconds, 4 seconds
                    multiplier: 2
            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%?queue_name=failed'

        routing:
            App\Mailer\Messenger\SendMessage\SendMessage: async
