version: '3.1'
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    working_dir: /application
    volumes:
      - .:/application
    environment:
      MYSQL_DATABASE: application
      MYSQL_USER: application
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
  nginx:
    image: nginx:alpine
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    build: docker/php-fpm
    working_dir: /application
    user: root
    environment:
      DATABASE_URL: mysql://application:123@mysql/application?serverVersion=8.0
      OAUTH2_SERVER_ENCRYPTION_KEY: i08x7tGW9MJtZ+KQyqV8vcxATCGmjH3yl4wOWFDnn3A=
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
  mailhog:
    image: mailhog/mailhog:latest
    command: -invite-jim
